/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRhRouteImport } from './routes/_authenticated/rh'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedLancamentoRouteImport } from './routes/_authenticated/lancamento'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated/comercial'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRhRoute = AuthenticatedRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLancamentoRoute = AuthenticatedLancamentoRouteImport.update({
  id: '/lancamento',
  path: '/lancamento',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/lancamento': typeof AuthenticatedLancamentoRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/rh': typeof AuthenticatedRhRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/lancamento': typeof AuthenticatedLancamentoRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/rh': typeof AuthenticatedRhRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/comercial': typeof AuthenticatedComercialRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/lancamento': typeof AuthenticatedLancamentoRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/rh': typeof AuthenticatedRhRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/historico'
    | '/lancamento'
    | '/marketing'
    | '/metas'
    | '/producao'
    | '/relatorio'
    | '/rh'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/historico'
    | '/lancamento'
    | '/marketing'
    | '/metas'
    | '/producao'
    | '/relatorio'
    | '/rh'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/comercial'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/historico'
    | '/_authenticated/lancamento'
    | '/_authenticated/marketing'
    | '/_authenticated/metas'
    | '/_authenticated/producao'
    | '/_authenticated/relatorio'
    | '/_authenticated/rh'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh': {
      id: '/_authenticated/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AuthenticatedRhRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lancamento': {
      id: '/_authenticated/lancamento'
      path: '/lancamento'
      fullPath: '/lancamento'
      preLoaderRoute: typeof AuthenticatedLancamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedLancamentoRoute: typeof AuthenticatedLancamentoRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedRhRoute: typeof AuthenticatedRhRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedComercialRoute: AuthenticatedComercialRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedLancamentoRoute: AuthenticatedLancamentoRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedRhRoute: AuthenticatedRhRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
